[package]
name = "vcd"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "vcd"
crate-type = ["cdylib"]
path = "src/parser.rs"